function [Height,ssEN_dbm,tx,txE,txN,txEN,UAVheightE,UAVheightN,sensorsiteE,sensorsiteN,sensorsiteNE,latr,lonr]=GenerateSimulationData(Startla1,Startlon1,UAVheight,UAVspeed,boxsize,sensordensity,sensornum,transmittedpower,sensorheight,receiversensitivity,pm)
%-----------generate UAV path------------------%
tx = txsite('Name','MathWorks', ...
        'Latitude', Startla1, ...
        'Longitude', Startlon1,...
        'AntennaHeight',UAVheight,'TransmitterPower',transmittedpower);
[lat1,lon1]=location(tx,[0:UAVspeed:(UAVspeed*floor(boxsize/UAVspeed))],0);%location at which to transmit signal to the east of the starting site
[lat2,lon2]=location(tx,[0:UAVspeed:(UAVspeed*floor(boxsize/UAVspeed))],90);%location at which to transmit signal to the north of the starting site
sensorsiteE=randi([0 boxsize],1,round(sensornum));
sensorsiteN=randi([0 boxsize],1,round(sensornum));
sensorsiteNE=(sensorsiteE.^2+sensorsiteN.^2).^(1/2);%get distance for positioning of sensors
for i=1:length(sensorsiteN)
    if (sensorsiteN(i)==0)&(sensorsiteE(i)==0)
        sensorsiteA(i)=0;
    else
    sensorsiteA(i)=(atan(sensorsiteN(i)/sensorsiteE(i))*360)/(2*pi);%get angle for sensor location calculation
    end
end
[latr,lonr]=location(tx,sensorsiteNE,sensorsiteA);%get the sensors' position
txE = txsite('Name','MathWorks', ...
        'Latitude', lat1, ...
        'Longitude', lon1,...
        'AntennaHeight',UAVheight,'TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another
HeightM=elevation(txE);
UAVheightE=UAVheight-HeightM;
txE = txsite('Name','MathWorks', ...
        'Latitude', lat1, ...
        'Longitude', lon1,...
        'AntennaHeight',UAVheightE','TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another
txN = txsite('Name','MathWorks', ...
        'Latitude', lat2, ...
        'Longitude', lon2,...
        'AntennaHeight',UAVheight,'TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another
HeightM=elevation(txN);
UAVheightN=UAVheight-HeightM;
txN = txsite('Name','MathWorks', ...
        'Latitude', lat2, ...
        'Longitude', lon2,...
        'AntennaHeight',UAVheightN','TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another
rx = rxsite('Name','Boston', ...
        'Latitude', latr, ...
        'Longitude',lonr, ...
         'ReceiverSensitivity', receiversensitivity,...
         'AntennaHeight',sensorheight); %generate random position of sensor nodes within the designated area
txEN = txsite('Name','MathWorks', ...
        'Latitude', [lat1;lat2], ...
        'Longitude', [lon1;lon2],...
        'AntennaHeight',UAVheight,'TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another    
HeightM=elevation(txEN);
UAVheightEN=UAVheight-HeightM;
txEN = txsite('Name','MathWorks', ...
        'Latitude', [lat1;lat2], ...
        'Longitude', [lon1;lon2],...
        'AntennaHeight',UAVheightEN','TransmitterPower',transmittedpower);%set one of the two UAV paths perpendicular to one another    
Height=elevation(rx)+sensorheight;%get height relative to sea level to each sensor
ssEN_dbm=sigstrength(rx,txEN,pm,'Map','gmted2010');%received signal strength of every receiver for each transmitter site.
end

